[package]
name = "workload-gen-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
walkdir = "2.5.0"
workload-gen = { path = "../workload-gen/" }
